Spitgranger/SyncMaster

.github/ISSUE_TEMPLATE/lect.md
.github/ISSUE_TEMPLATE/sup_meet.md
.github/ISSUE_TEMPLATE/ta_meet.md
.github/ISSUE_TEMPLATE/team_meet.md
docs/DevelopmentPlan/DevelopmentPlan.md

merges commits to main to developmentplan branch. This includes the developmentplan.md file.

merge updates to main to developmentplan branch

---

LICENSE

merging to keep both branches synced, in hopes to avoid merge conflicts.

merges updated license information to developmentplan branch

---

docs/DevelopmentPlan/DevelopmentPlan.md

adds expectations section of dev plan
corresponds to https://github.com/Spitgranger/capstone/issues/23

Dev Plan - add expectations

---

docs/DevelopmentPlan/DevelopmentPlan.md

Add stay on track section of dev plan
corresponds to https://github.com/Spitgranger/capstone/issues/24

Dev Plan - Add Stay On Track Section

---

docs/DevelopmentPlan/DevelopmentPlan.md

This PR adds the acceptable excuses section to the development plan.
Resolve #19

feat(docs): added acceptable excuses in dev plan

---

docs/DevelopmentPlan/DevelopmentPlan.md

This PR adds the licence choice and justification to the development plan.
Resolves: #19

feat(docs): added licence section to dev plan #19

---

docs/DevelopmentPlan/DevelopmentPlan.md

This PR adds the Coding standard section to the development plan.
Resolves #19

feat(docs):added coding standard to dev plan #19

---

docs/DevelopmentPlan/DevelopmentPlan.md
docs/ProblemStatementAndGoals/ProblemStatement.md

ProblemStatement.md:
1.1 Problem
1.3 Stakeholders
1.4 Environment
4 Challenge Level and Extras
Appendix - Reflection
DevelopmentPlan.md:
1 Confidential Information
2 IP to protect
4 Team meeting plan
Appendix - Quality
Appendix - Decision Making
Introductory Blurb

feat(docs): adds problem statement and Mitchell's sections

---

docs/DevelopmentPlan/DevelopmentPlan.md

Expected Technologies Section of the document
Corresponds to https://github.com/Spitgranger/capstone/issues/15

Dev Plan - Add Expected Technologies Section

---

docs/DevelopmentPlan/DevelopmentPlan.md

This PR adds answers for question 1 and question 2 of the reflection in the development plan. 
Resolves: #19

feat(docs): added 2 selection for the reflection #19

---

docs/DevelopmentPlan/DevelopmentPlan.md

Just to be consistent across all of the reflection question responses

Dev Plan - Fix formatting of reflection questions to include bullet points

---

docs/DevelopmentPlan/DevelopmentPlan.md

This PR adds the risks and the POC plan.
Resolves #47

feat(docs): added POC risks and demo plan

---

docs/DevelopmentPlan/DevelopmentPlan.md

#40
Added git workflow plan to development plan document

Added git workflow plan to development plan

---

docs/DevelopmentPlan/DevelopmentPlan.md

#45
Added code of conduct and conflict resolution plan under attitude section

Added code of conduct and conflict resolution plan

---

.github/ISSUE_TEMPLATE/task.md

This PR adds a template for Tasks.

feat: added template for task

---

docs/SRS-Volere/SRS.tex

This PR adds requirements for migration to the new system
Resolves #76

feat(docs): SRS added migration to the new product requirements

---

docs/SRS-Volere/SRS.tex

This PR adds the requirements in the usability and humanity section in the SRS.
Resolves #65

feat(docs): Add requirements for usability and humanity

---

docs/SRS-Volere/SRS.tex

merge stakeholders sections into main branch.

feat(docs/SRS): Add Section 2: Stakeholders

---

docs/SRS-Volere/SRS.tex

This PR adds some formal definitions and requirements to the SRS

feat(docs): added some formal specifications to SRS

---

docs/SRS-Volere/SRS.tex

Apparently, the reflection questions are out of sync according to https://gitlab.cas.mcmaster.ca/courses/capstone/-/issues/3, so I'm updating them. Not sure if we actually need the new questions maybe we should ask the TA? I'm just making the PR so we can quickly merge if needed.

SRS - fix reflection questions

---

docs/SRS-Volere/SRS.tex

Added points from our meeting and the notes Akshit took.
closes #80

Added possible solutions

---

docs/SRS-Volere/SRS.tex

relates to https://github.com/Spitgranger/capstone/issues/109

SRS - add my reflection answers

---

docs/SRS-Volere/SRS.tex

This PR adds a natural language complement to the formal specifications. See #63

feat(docs): added more functional requirements

---

docs/SRS-Volere/SRS.tex

This PR adds the information relating to requirements in Waiting Room
Resolves #79

feat(docs): updated waiting room with N/A #79

---

docs/SRS-Volere/SRS.tex

This PR adds the missing accessibility requirement.

feat(docs): added accessibility requirement

---

docs/SRS-Volere/SRS.tex

This PR adds my reflection to the SRS
Resolves #126

feat(docs): complete my reflection #126

---

docs/SRS-Volere/SRS.tex

#66 
*Added performance requirements

Added performance requirements

---

docs/SRS-Volere/SRS.tex
docs/SRS-Volere/cite.bib

This PR adds bibtex citations to the document. Looking at the rubric we need to put some citations in to get marks. See if there are any to add (for example regulations)

feat(docs): added citation for volere template

---

docs/SRS-Volere/SRS.tex

Added reflection

---

docs/HazardAnalysis/HazardAnalysis.tex

Adds introduction and my FMEA table parts

Add Introduction, and Initial FMEA Table

---

docs/HazardAnalysis/HazardAnalysis.tex

Minimal assumptions added, considering all other points of failure will be addressed in the doc. Can add more if we assume a point of failure will be detected, mitigated or resolved by someone/something outside the application.
closes #146

Added assumptions

---

docs/HazardAnalysis/HazardAnalysis.tex

This PR adds the Scope and Purpose section to the hazard analysis
Resolves #150

feat(docs): added scope and purpose section for hazard analysis #150

---

docs/HazardAnalysis/HazardAnalysis.tex

Added failure modes: User unable to complete 2FA and User unable to access website

Added 2 failure modes

---

docs/HazardAnalysis/HazardAnalysis.tex

The PR adds two points to the FEMA table.

feat(docs): added points to FEMA table

---

docs/HazardAnalysis/HazardAnalysis.tex

#145
* Added system components and boundaries - section 3

Added system components and boundaries

---

docs/HazardAnalysis/HazardAnalysis.tex

we should aim to implement all requirements documented.

Added a roadmap

---

docs/VnVPlan/VnVPlan.tex

This PR adds the validation and verification team section to the VnV plan
Resolves #182

feat(docs): added validation and verification team

---

docs/VnVPlan/VnVPlan.tex

Links to SRS for acronyms. Short introduction paragraph outlining the document contents.

Adds Section 1  - abbreviations, symbols, acronyms, and general introduction

---

docs/VnVPlan/VnVPlan.tex

Added tests for Operational and Environmental NFRS

Added tests for OE

---

docs/VnVPlan/VnVPlan.tex

Added plan for testing implementation

Added Implementation Verification Plan section

---

docs/VnVPlan/VnVPlan.tex

added tests, updated matrix
also changed the formatting at the beginning of the doc and some typos in other sections.

Added safety and security tests.

---

docs/SRS-Volere/SRS.tex
docs/VnVPlan/VnVPlan.tex

#189 
Added tests for functional requirements

Added tests for functional requirements

---

docs/VnVPlan/VnVPlan.tex

Update security tests

---

docs/VnVPlan/VnVPlan.tex

Add a overview of our plans

---

docs/SRS-Volere/SRS.tex
docs/VnVPlan/VnVPlan.tex

#199 
Added tests for performance requirements

Added tests for performance requirements

---

src/poc/client/poc-client/package-lock.json
src/poc/client/poc-client/package.json
src/poc/client/poc-client/src/app/(verification)/[userId]/verify-location/page.tsx
src/poc/client/poc-client/src/components/test/apitest.tsx
src/poc/client/poc-client/src/utils/hooks/useSocket.ts
src/poc/client/poc-client/src/utils/socket.ts
src/poc/client/poc-client/src/utils/wrapper.tsx

This PR adds the socket context for the client.
Resolves #270 
Apologies for the formatting changes.

feat(poc): create socket context hook for client application

---

src/poc/client/poc-client/package-lock.json
src/poc/client/poc-client/package.json
src/poc/client/poc-client/src/app/(verification)/[userId]/verify-location/page.tsx
src/poc/client/poc-client/src/components/test/apitest.tsx
src/poc/client/poc-client/src/utils/hooks/useSocket.ts
src/poc/client/poc-client/src/utils/socket.ts
src/poc/client/poc-client/src/utils/wrapper.tsx
src/poc/server/poc-server/src/controllers/dashboard.ts
src/poc/server/poc-server/src/index.ts
src/poc/server/poc-server/src/middleware/auth.ts
src/poc/server/poc-server/src/routes/dashboard.ts

This PR adds an auth middleware and an endpoint protected by it to serve dummy data to the dashboard.
Resolves #275 #276

feat(poc): add authentication middleware

---

docs/Design/SoftArchitecture/MG.tex

This PR adds sections 2 through 5 to the module guide Resolves #296 #297 #298 #299

docs(MG) Sections 2 to 5

---

docs/Design/SoftDetailedDes/MIS.tex

This PR adds the module decomposition from the MG to the MIS.
Resolves #309

feat(docs): MIS add module decomposition #309

---

docs/Design/SoftArchitecture/MG.tex

Added Timeline to MG
closes #305

docs(MG): Add MG schedule

---

docs/Design/SoftArchitecture/MG.tex

Renames Blob Storage to File Storage

fix(docs): renamed blob storage to file storage

---

.github/workflows/backend-checks.yaml
src/backend/service/models/db/document.py

fixes linters passing even though a check failed (particularly with pylint)

fix(actions): make backend-checks fail on errors

---

infrastructure/backend.yaml
src/backend/service/routes/protected/users.py

Add the training completion date as a optional user attribute.
Resolves #423

feat(rev1): add user training completion date as user attribute

---

docs/VnVReport/VnVReport.tex

Added trace to modules for functional requirements

feat(docs): added trace to modules for FRs

---

infrastructure/backend.yaml
src/backend/service/handler.py
src/backend/service/routes/protected/documents.py
src/backend/service/routes/protected/site_visits.py
src/backend/service/user_authentication/user_authentication.py
src/backend/service/util.py
test/backend/unit/fixtures/api_gateway_event_v1.py
test/backend/unit/fixtures/cognito.py
test/backend/unit/routes/test_site_visits.py

Make roles use cognito user groups, in anticipation for user requests
Resolves #480

feat(rev1): migrate user roles to use cognito user groups

---

infrastructure/backend.yaml

I've tested that the headers get added now when I make a request with no auth token, so this should work

fix(rev1): Fix cors issues on authorization

---

src/backend/service/exceptions.py
src/backend/service/routes/protected/documents.py
src/backend/service/routes/protected/site.py
src/backend/service/routes/protected/site_visits.py
src/backend/service/routes/protected/user_requests.py
src/backend/service/routes/unprotected/auth.py
src/backend/service/util.py

just adds a function for verifying user permissions, and parsing the epoch request time
mostly just concerned that they see this repeated code all over the place and consider it bad quality, it's not like a big deal or anything

refactor(rev1): make common utilities into functions

---

infrastructure/backend.yaml

Forgot these in earlier PR and didn't realize until I deployed to AWS

fix: infrastructure changes to allow admin cognito access

---

src/client-contractor-portal/src/components/SignInForm/index.tsx
src/client-contractor-portal/src/components/layouts/PortalLayout.tsx
src/client-contractor-portal/src/pages/portal/acknowledgement.tsx
src/client-contractor-portal/src/pages/portal/documents/general/[[...slug]].tsx
src/client-contractor-portal/src/pages/portal/documents/index.tsx
src/client-contractor-portal/src/pages/portal/documents/specific/[[...slug]].tsx
src/client-contractor-portal/src/state/user/userSlice.ts

Updated Auth logic
Integrated Documents from admin portal
Made Avatar functional

Frontend contractor portal final demo

---

.github/workflows/deploy-backend.yaml

Create backend deploy action.
Resolves #489

feat(final): add deploy action for SyncMaster backend

---

scripts/frontend/deploy.sh

Not using SSO profile in the action here, setup to work with AWS credentials.

fix: remove profile from cli args

---

CodeOfConduct.md
README.md
docs/Design/README.md
docs/Design/SoftArchitecture/README.md
docs/Design/SoftDetailedDes/README.md
docs/DevelopmentPlan/README.md
docs/Extras/README.md
docs/Extras/UsabilityTesting/README.md
docs/Extras/UserManual/README.md
docs/HazardAnalysis/README.md
docs/Presentations/D0_ProofOfConceptDemo/README.md
docs/Presentations/D1_Rev0Demo/README.md
docs/Presentations/D2_FinalPresentation/README.md
docs/ProblemStatementAndGoals/README.md
docs/README.md
docs/ReflectAndTrace/README.md
docs/SRS-Volere/README.md
docs/VnVPlan/README.md
docs/VnVReport/README.md
infrastructure/README.md
refs/README.md
scripts/README.md
scripts/backend/README.md
scripts/frontend/README.md
src/README.md
test/README.md

I was reading through some of the rubrics for the final docs, and some of them mention having up to date readme's, so I went through and updated a bunch of them

docs(rev1): update all readmes

---

docs/ReflectAndTrace/ReflectAndTrace.tex

Added content to sections 7.1 and 7.2

Update ReflectAndTrace.tex: Sections 7.1 and 7.2

---

src/client-admin-portal/src/components/SiteCardComponent/index.tsx
src/client-admin-portal/src/components/SiteCardManageComponent/index.tsx
src/client-admin-portal/src/components/SiteVisitsComponent/index.tsx

implemented the changes suggested from user feedback.

Expo/admin portal/user feedback
